In [1]:
from sklearn.neighbors import KNeighborsRegressor

In [13]:
def make_grid(X,y,res):
    y_min = y.min()-0.2
    y_max = y.max()+0.2
    x_min = X.min()-0.2
    x_max = X.max()+0.2
    x_arr = np.linspace(x_min,x_max,res)
    y_arr = np.linspace(y_min,y_max,res)
    xx,yy = np.meshgrid(x_arr,y_arr)  
    return xx,yy


In [ ]:


def nearest_neighbors(dataset, neighbors = 5, resolution='standard', coordinate_type='euclidean',verbose='False'):
    if coordinate_type == 'latlong_small':
        """
            Assume that the Earth is a Sphere, and use polar coordinates
            $| \vec{r_2}− \vec{r_1}| ≈ \text{R }\times \sqrt[]{(Lat_2 - Lat_1)^{2} + (Long_2 - Long_1)^{2}}$
        """
        return "To be done later"
    if coordinate_type == 'latlong_large':
        """
            Code to be written after understanding all the projections.
        """
        return "To be done later"
    if coordinate_type=="euclidean":
        knn = KNeighborsRegressor(n_neighbors=neighbors)
        knn.fit(dataset[:,:2],dataset[:,2])
        
        if resolution=='high':
            xx,yy = make_grid(X,y,1000)
            
        elif resolution=='low':
            xx,yy = make_grid(X,y,10)
            
        elif resolution=='standard':
            xx,yy = make_grid(X,y,100)
            
        new_grid = np.zeros((len(xx),len(yy)))
        
        for i in range(len(xx[0])):
            for j in range(len(yy)):

In [11]:
knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(data[:,:2],data[:,2])

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform')

In [12]:
knn.predict([[12.5,14]])

array([135.4])

In [14]:
xx,yy = make_grid(data[:,0],data[:,1],100)

In [8]:
data = np.array(df[['longitude','latitude','value']])

In [17]:
new_grid = np.zeros((len(xx),len(yy)))

In [10]:
data[:,2]

array([194., 267., 273., 129., 176., 172., 168., 105., 203., 192.,  95.,
       148., 203., 221., 141., 192., 203., 152., 185., 290., 273., 173.,
       269., 160.,  78., 211., 252., 133.,  77.,  96.])

In [4]:
import pandas as pd
import numpy as np
df = pd.read_csv('../test_data/30-03-18.csv')
df.head(10)

Unnamed: 0                                   location parameter  value  \
0        4087     Jawaharlal Nehru Stadium, Delhi - DPCC      pm25  194.0   
1        3930                  Sonia Vihar, Delhi - DPCC      pm25  267.0   
2        4020                       Narela, Delhi - DPCC      pm25  273.0   
3        4057                    Najafgarh, Delhi - DPCC      pm25  129.0   
4        3998              NSIT Dwarka, New Delhi - CPCB      pm25  176.0   
5        4104             Dwarka-Sector 8, Delhi - DPCC       pm25  172.0   
6        4009                R K Puram, New Delhi - DPCC      pm25  168.0   
7        4099  IGI Airport Terminal - 3, New Delhi - IMD      pm25  105.0   
8        4074                Okhla Phase-2, Delhi - DPCC      pm25  203.0   
9        4068                  Nehru Nagar, Delhi - DPCC      pm25  192.0   

    latitude  longitude  
0  28.581197  77.234291  
1  28.739434  77.245721  
2  28.822931  77.101961  
3  28.620806  76.991463  
4  28.609090  77.032541  
5  28.570859  77.072196  
6  28.564610  77.167010  
7  28.562776  77.118005  
8  28.530782  77.272404  
9  28.563827  77.260750

In [24]:
knn.predict([[77,29]])

array([219.])

In [26]:
for j in range(len(yy[:,0])):
    for i in range(len(xx)):
        new_grid[i][j] = float(knn.predict([[xx[0][i],yy[j][0]]]))

In [27]:
new_grid

array([[135.4, 135.4, 135.4, ..., 171.6, 171.6, 171.6],
       [135.4, 135.4, 135.4, ..., 171.6, 171.6, 191. ],
       [135.4, 135.4, 135.4, ..., 171.6, 191. , 191. ],
       ...,
       [171.6, 171.6, 171.6, ..., 236.4, 236.4, 236.4],
       [171.6, 171.6, 171.6, ..., 236.4, 236.4, 236.4],
       [171.6, 171.6, 175.4, ..., 236.4, 236.4, 236.4]])